# This is a basic workflow to help you get started with Actions

name: Deploy to production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
    # branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]
  workflow_dispatch:

jobs:
  write_artifact:
    name: Versioning workflow run
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo 1 > version.txt
      - name: Upload version number
        uses: actions/upload-artifact@v3
        with:
          name: version
          path: version.txt
